### ISSUE TITLE
Delay or keybindings

### ISSUE THREAD

**Issue by elch10** [Venthe/vscode-fauxpilot#1]
Thanks for extension. But current behavior like "load testing". Because every entered symbol generates a query to the model, even If I haven't finished enter word. And so "ping" just increases.

Can we control requests to model may be with keybindings ? Or may be after some delay after last symbol was entered ?

**Comment by Venthe** [comment]
At this moment I don't know how easy it would be. While the whole delaying part is easy with the libraries in used to (rxjs) I don't know how to implement it sensibly. Not to mention that rxjs seems like an overkill for a simple delay.

I'll try to read about how vscode works.

**Comment by Venthe** [comment]
I have an idea how to do it in an naive way. I'm not used to code extensions & it's been ages since I had to mix async and sync code. There might be a better way; but for PoC it will work.

1. Save to global temp `globalPrompt`
2. sleep for X
3. Check if the `globalPrompt` matches `prompt`
  1. YES: Ask the API for the suggestions
  2. NO: User had changed the input, immediately return without suggestions

I will not have a chance to work on this up until friday, so I hope that the race condition will not occur. In a typical fashion I'd use observable pattern... but I have no clue how to use it with the code that both provides data and expect results. The behaviourSubject should work as well, but I had some issues with it and as such I'm more willing to do a brutally simplistic solution for now

**Comment by Venthe** [comment]
@elch10 Can you test the https://github.com/Venthe/vscode-fauxpilot/tree/wip-1 branch?
